//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.CourseRegisterReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://trainings.ttu.ee", ConfigurationName="CourseRegisterReference.ITrainingsSchedule")]
    public interface ITrainingsSchedule {
        
        // CODEGEN: Generating message contract since message CoursesListRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://trainings.ttu.ee/CoursesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XRoadIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CourseShort[]))]
        ConsoleApp1.CourseRegisterReference.CoursesListResponse CoursesList(ConsoleApp1.CourseRegisterReference.CoursesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainings.ttu.ee/CoursesList", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CoursesListResponse> CoursesListAsync(ConsoleApp1.CourseRegisterReference.CoursesListRequest request);
        
        // CODEGEN: Generating message contract since message CourseDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://trainings.ttu.ee/CourseDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XRoadIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CourseShort[]))]
        ConsoleApp1.CourseRegisterReference.CourseDetailsResponse CourseDetails(ConsoleApp1.CourseRegisterReference.CourseDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://trainings.ttu.ee/CourseDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CourseDetailsResponse> CourseDetailsAsync(ConsoleApp1.CourseRegisterReference.CourseDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadClientIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadLocalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadGlobalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityServerIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadCentralServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityCategoryIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadClientIdentifierType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string xRoadInstanceField;
        
        private string memberClassField;
        
        private string memberCodeField;
        
        private string subsystemCodeField;
        
        private string groupCodeField;
        
        private string serviceCodeField;
        
        private string serviceVersionField;
        
        private string securityCategoryCodeField;
        
        private string serverCodeField;
        
        private XRoadObjectType objectTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xRoadInstance {
            get {
                return this.xRoadInstanceField;
            }
            set {
                this.xRoadInstanceField = value;
                this.RaisePropertyChanged("xRoadInstance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string memberClass {
            get {
                return this.memberClassField;
            }
            set {
                this.memberClassField = value;
                this.RaisePropertyChanged("memberClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string memberCode {
            get {
                return this.memberCodeField;
            }
            set {
                this.memberCodeField = value;
                this.RaisePropertyChanged("memberCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string subsystemCode {
            get {
                return this.subsystemCodeField;
            }
            set {
                this.subsystemCodeField = value;
                this.RaisePropertyChanged("subsystemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string groupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
                this.RaisePropertyChanged("groupCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("serviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("serviceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string securityCategoryCode {
            get {
                return this.securityCategoryCodeField;
            }
            set {
                this.securityCategoryCodeField = value;
                this.RaisePropertyChanged("securityCategoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string serverCode {
            get {
                return this.serverCodeField;
            }
            set {
                this.serverCodeField = value;
                this.RaisePropertyChanged("serverCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public XRoadObjectType objectType {
            get {
                return this.objectTypeField;
            }
            set {
                this.objectTypeField = value;
                this.RaisePropertyChanged("objectType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public enum XRoadObjectType {
        
        /// <remarks/>
        MEMBER,
        
        /// <remarks/>
        SUBSYSTEM,
        
        /// <remarks/>
        SERVER,
        
        /// <remarks/>
        GLOBALGROUP,
        
        /// <remarks/>
        LOCALGROUP,
        
        /// <remarks/>
        SECURITYCATEGORY,
        
        /// <remarks/>
        SERVICE,
        
        /// <remarks/>
        CENTRALSERVICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trainings.ttu.ee")]
    public partial class Course : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string locationField;
        
        private System.DateTime dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trainings.ttu.ee")]
    public partial class CourseShort : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadLocalGroupIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadGlobalGroupIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityServerIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadCentralServiceIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityCategoryIdentifierType : XRoadIdentifierType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadServiceIdentifierType : XRoadIdentifierType {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoursesList", WrapperNamespace="http://trainings.ttu.ee", IsWrapped=true)]
    public partial class CoursesListRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trainings.ttu.ee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trainings.ttu.ee", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Date;
        
        public CoursesListRequest() {
        }
        
        public CoursesListRequest(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, string Name, System.DateTime Date) {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.Name = Name;
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CoursesListResponse", WrapperNamespace="http://trainings.ttu.ee", IsWrapped=true)]
    public partial class CoursesListResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trainings.ttu.ee", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ConsoleApp1.CourseRegisterReference.CourseShort[] Courses;
        
        public CoursesListResponse() {
        }
        
        public CoursesListResponse(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, ConsoleApp1.CourseRegisterReference.CourseShort[] Courses) {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.Courses = Courses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CourseDetails", WrapperNamespace="http://trainings.ttu.ee", IsWrapped=true)]
    public partial class CourseDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Id", Namespace="http://trainings.ttu.ee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id1;
        
        public CourseDetailsRequest() {
        }
        
        public CourseDetailsRequest(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, int Id1) {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.Id1 = Id1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CourseDetailsResponse", WrapperNamespace="http://trainings.ttu.ee", IsWrapped=true)]
    public partial class CourseDetailsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://trainings.ttu.ee", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApp1.CourseRegisterReference.Course Course;
        
        public CourseDetailsResponse() {
        }
        
        public CourseDetailsResponse(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, ConsoleApp1.CourseRegisterReference.Course Course) {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.Course = Course;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainingsScheduleChannel : ConsoleApp1.CourseRegisterReference.ITrainingsSchedule, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainingsScheduleClient : System.ServiceModel.ClientBase<ConsoleApp1.CourseRegisterReference.ITrainingsSchedule>, ConsoleApp1.CourseRegisterReference.ITrainingsSchedule {
        
        public TrainingsScheduleClient() {
        }
        
        public TrainingsScheduleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainingsScheduleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingsScheduleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingsScheduleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.CourseRegisterReference.CoursesListResponse ConsoleApp1.CourseRegisterReference.ITrainingsSchedule.CoursesList(ConsoleApp1.CourseRegisterReference.CoursesListRequest request) {
            return base.Channel.CoursesList(request);
        }
        
        public ConsoleApp1.CourseRegisterReference.CourseShort[] CoursesList(ref ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ref ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, ref string userId, ref string id, ref string protocolVersion, string Name, System.DateTime Date) {
            ConsoleApp1.CourseRegisterReference.CoursesListRequest inValue = new ConsoleApp1.CourseRegisterReference.CoursesListRequest();
            inValue.client = client;
            inValue.service = service;
            inValue.userId = userId;
            inValue.id = id;
            inValue.protocolVersion = protocolVersion;
            inValue.Name = Name;
            inValue.Date = Date;
            ConsoleApp1.CourseRegisterReference.CoursesListResponse retVal = ((ConsoleApp1.CourseRegisterReference.ITrainingsSchedule)(this)).CoursesList(inValue);
            client = retVal.client;
            service = retVal.service;
            userId = retVal.userId;
            id = retVal.id;
            protocolVersion = retVal.protocolVersion;
            return retVal.Courses;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CoursesListResponse> ConsoleApp1.CourseRegisterReference.ITrainingsSchedule.CoursesListAsync(ConsoleApp1.CourseRegisterReference.CoursesListRequest request) {
            return base.Channel.CoursesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CoursesListResponse> CoursesListAsync(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, string Name, System.DateTime Date) {
            ConsoleApp1.CourseRegisterReference.CoursesListRequest inValue = new ConsoleApp1.CourseRegisterReference.CoursesListRequest();
            inValue.client = client;
            inValue.service = service;
            inValue.userId = userId;
            inValue.id = id;
            inValue.protocolVersion = protocolVersion;
            inValue.Name = Name;
            inValue.Date = Date;
            return ((ConsoleApp1.CourseRegisterReference.ITrainingsSchedule)(this)).CoursesListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.CourseRegisterReference.CourseDetailsResponse ConsoleApp1.CourseRegisterReference.ITrainingsSchedule.CourseDetails(ConsoleApp1.CourseRegisterReference.CourseDetailsRequest request) {
            return base.Channel.CourseDetails(request);
        }
        
        public ConsoleApp1.CourseRegisterReference.Course CourseDetails(ref ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ref ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, ref string userId, ref string id, ref string protocolVersion, int Id1) {
            ConsoleApp1.CourseRegisterReference.CourseDetailsRequest inValue = new ConsoleApp1.CourseRegisterReference.CourseDetailsRequest();
            inValue.client = client;
            inValue.service = service;
            inValue.userId = userId;
            inValue.id = id;
            inValue.protocolVersion = protocolVersion;
            inValue.Id1 = Id1;
            ConsoleApp1.CourseRegisterReference.CourseDetailsResponse retVal = ((ConsoleApp1.CourseRegisterReference.ITrainingsSchedule)(this)).CourseDetails(inValue);
            client = retVal.client;
            service = retVal.service;
            userId = retVal.userId;
            id = retVal.id;
            protocolVersion = retVal.protocolVersion;
            return retVal.Course;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CourseDetailsResponse> ConsoleApp1.CourseRegisterReference.ITrainingsSchedule.CourseDetailsAsync(ConsoleApp1.CourseRegisterReference.CourseDetailsRequest request) {
            return base.Channel.CourseDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.CourseRegisterReference.CourseDetailsResponse> CourseDetailsAsync(ConsoleApp1.CourseRegisterReference.XRoadClientIdentifierType client, ConsoleApp1.CourseRegisterReference.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, int Id1) {
            ConsoleApp1.CourseRegisterReference.CourseDetailsRequest inValue = new ConsoleApp1.CourseRegisterReference.CourseDetailsRequest();
            inValue.client = client;
            inValue.service = service;
            inValue.userId = userId;
            inValue.id = id;
            inValue.protocolVersion = protocolVersion;
            inValue.Id1 = Id1;
            return ((ConsoleApp1.CourseRegisterReference.ITrainingsSchedule)(this)).CourseDetailsAsync(inValue);
        }
    }
}
